# Generated by Django 4.1.7 on 2023-03-22 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_basket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descripton',
            new_name='description',
        ),
    ]
